name = input("What is your name? ")
food = input("What is your favorite food? ")
music = input("What is your favorite music? ")
location = input("Where do you live? ")
print()

print("You are")
print(name)
print("You're probably hungry for")
print(food)
print("and you're definitely getting your groove on to")
print(music)
print("living in the amazing")
print(location)
